[env:LoRaBlue]
extends = nrf52840_base
board = adafruit_itsybitsy_nrf52840
build_flags = ${nrf52840_base.build_flags} -I variants/LoRaBlue -D LoRaBlue
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m4/fpv4-sp-d16-hard"
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/LoRaBlue>
lib_deps = 
  ${nrf52840_base.lib_deps}
upload_protocol = nrfutil